USE banco;

CREATE TABLE IF NOT EXISTS `user` (
    id INT AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(120) NOT NULL,
    session_id TEXT NOT NULL,
    password VARCHAR(40) NOT NULL
);

ALTER TABLE `user`
    MODIFY COLUMN email VARCHAR(120) NOT NULL,
    MODIFY COLUMN session_id TEXT NOT NULL,
    MODIFY COLUMN password VARCHAR(40) NOT NULL;
